# Jarvis/project.yml
# Spec lives inside the Jarvis/ folder.
# It compiles EVERY Swift file under Sources/AppModule (App, Chat, Models, Privacy, services, Settings, Vision, Voice),
# links the local Swift package product AppModule, and expects an Info.plist next to JarvisApp.swift.

name: Jarvis
options:
  minimumXcodeGenVersion: 2.38.0
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  BASE_SDK: iphoneos
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"

packages:
  # Local Swift package with Package.swift at repo root (one level up from Jarvis/)
  appmodule-local:
    path: ..

targets:
  Jarvis:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    # Include all source code under Sources/AppModule (recursively)
    # and also add explicit groups for the subfolders shown in your screenshots.
    sources:
      # Catch‑all include
      - path: Sources/AppModule
        name: AppModuleAll
        excludes:
          - "../Scripts/**"
          - "**/*.md"

      # Explicit subfolders for cleaner grouping in Xcode’s navigator
      - path: Sources/AppModule/App
        name: App
      - path: Sources/AppModule/Chat
        name: Chat
      - path: Sources/AppModule/Models
        name: Models
      - path: Sources/AppModule/Privacy
        name: Privacy
      - path: Sources/AppModule/services
        name: services
      - path: Sources/AppModule/Settings
        name: Settings
      - path: Sources/AppModule/Vision
        name: Vision
      - path: Sources/AppModule/Voice
        name: Voice

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mistico06.jarvis
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      TARGETED_DEVICE_FAMILY: "1,2"
      SWIFT_VERSION: 5.0
      ENABLE_PREVIEWS: YES

      # Place this file alongside JarvisApp.swift (create it if missing)
      INFOPLIST_FILE: Sources/AppModule/App/Info.plist

      # If you later add entitlements:
      # CODE_SIGN_ENTITLEMENTS: Sources/AppModule/App/Jarvis.entitlements

      # If you later link prebuilt libs, uncomment and customize:
      # LIBRARY_SEARCH_PATHS:
      #   - "$(inherited)"
      #   - "$(PROJECT_DIR)/dist/lib"
      # OTHER_LDFLAGS:
      #   - "-Wl,-all_load"
      #   - "-lmodel_iphone"
      #   - "-lmlc_llm"
      #   - "-ltvm_runtime"
      #   - "-ltokenizers_cpp"
      #   - "-lsentencepiece"
      #   - "-ltokenizers_c"

    dependencies:
      - package: appmodule-local
        product: AppModule

    scheme:
      testTargets: []
      gatherCoverageData: false
