# Jarvis/project.yml — spec and Package.swift both live inside Jarvis/

name: Jarvis
options:
  minimumXcodeGenVersion: 2.38.0
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  BASE_SDK: iphoneos
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"

packages:
  # Local Swift package is in the SAME folder as this spec
  appmodule-local:
    path: .

targets:
  Jarvis:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    # Include all code under Sources/AppModule (recursively)
    sources:
      - path: Sources/AppModule
        name: AppModuleAll
        excludes:
          - "../Scripts/**"
          - "**/*.md"
      - path: Sources/AppModule/App
        name: App
      - path: Sources/AppModule/Chat
        name: Chat
      - path: Sources/AppModule/Models
        name: Models
      - path: Sources/AppModule/Privacy
        name: Privacy
      - path: Sources/AppModule/services
        name: services
      - path: Sources/AppModule/Settings
        name: Settings
      - path: Sources/AppModule/Vision
        name: Vision
      - path: Sources/AppModule/Voice
        name: Voice

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mistico06.jarvis
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      TARGETED_DEVICE_FAMILY: "1,2"
      SWIFT_VERSION: 5.0
      ENABLE_PREVIEWS: YES
      INFOPLIST_FILE: Sources/AppModule/App/Info.plist
      # CODE_SIGN_ENTITLEMENTS: Sources/AppModule/App/Jarvis.entitlements

    dependencies:
      - package: appmodule-local
        product: AppModule

    scheme:
      testTargets: []
      gatherCoverageData: false
