name: Build App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: List available schemes
        working-directory: Jarvis
        run: xcodebuild -list

      - name: Build iOS package with full logging
        working-directory: Jarvis
        run: |
          set -o pipefail
          xcodebuild clean build \
            -scheme Jarvis \
            -destination "generic/platform=iOS" \
            IPHONEOS_DEPLOYMENT_TARGET=17.0 \
            CODE_SIGN_STYLE=Automatic \
            -verbose 2>&1 | tee xcodebuild.log

      - name: Upload xcodebuild log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-log
          path: Jarvis/xcodebuild.log

      - name: Show compilation errors if build failed
        if: failure()
        working-directory: Jarvis
        run: |
          echo "=== COMPILATION ERRORS ==="
          grep -A 5 -B 5 "error:" xcodebuild.log || true
          echo "=== FATAL ERRORS ==="
          grep -A 5 -B 5 "fatal error:" xcodebuild.log || true
