name: Build App (IPA for AltStore)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: List available schemes
        working-directory: Jarvis
        run: xcodebuild -list

      # Build + Archive (unsigned) for generic iOS device
      - name: Archive (Release, unsigned)
        working-directory: Jarvis
        env:
          SCHEME: Jarvis           # <-- Change if your scheme differs
          ARCHIVE_PATH: ${{ github.workspace }}/Jarvis/build/Jarvis.xcarchive
        run: |
          set -o pipefail
          xcodebuild clean archive \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_ALLOWED=NO \
            IPHONEOS_DEPLOYMENT_TARGET=16.0 \
            ENABLE_BITCODE=NO \
            | xcbeautify --renderer github-actions || EXIT_CODE=$?
          # Save a full log snapshot for debugging if needed
          xcodebuild -showBuildSettings -scheme "$SCHEME" > xcodebuild.log 2>&1 || true
          exit ${EXIT_CODE:-0}

      - name: Create unsigned ExportOptions.plist
        working-directory: Jarvis
        run: |
          cat > ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>developer-id</string>
            <key>compileBitcode</key><false/>
            <key>signingStyle</key><string>manual</string>
            <key>destination</key><string>export</string>
            <key>stripSwiftSymbols</key><true/>
            <key>manageAppVersionAndBuildNumber</key><false/>
          </dict>
          </plist>
          EOF

      # Export an unsigned .ipa suitable for AltStore
      - name: Export IPA (unsigned)
        working-directory: Jarvis
        env:
          ARCHIVE_PATH: ${{ github.workspace }}/Jarvis/build/Jarvis.xcarchive
          EXPORT_DIR: ${{ github.workspace }}/Jarvis/build/export
        run: |
          set -o pipefail
          mkdir -p "$EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$EXPORT_DIR" \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO \
            | tee export.log
          echo "Exported files:"
          ls -la "$EXPORT_DIR"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: Jarvis/build/export/*.ipa
          if-no-files-found: error

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            Jarvis/xcodebuild.log
            Jarvis/export.log

      - name: Show compilation errors if build failed
        if: failure()
        working-directory: Jarvis
        run: |
          echo "=== COMPILATION ERRORS ==="
          grep -A 8 -B 8 "error:" xcodebuild.log || true
          echo "=== FATAL ERRORS ==="
          grep -A 8 -B 8 "fatal error:" xcodebuild.log || true
