name: Build App (IPA for AltStore)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: List available schemes
        working-directory: Jarvis
        run: xcodebuild -list

      - name: Archive (Release, unsigned)
        working-directory: Jarvis
        env:
          SCHEME: Jarvis
          ARCHIVE_PATH: ${{ github.workspace }}/Jarvis/build/Jarvis.xcarchive
        run: |
          set -o pipefail
          xcodebuild clean archive \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            IPHONEOS_DEPLOYMENT_TARGET=16.0 \
            ENABLE_BITCODE=NO \
            | xcbeautify --renderer github-actions || EXIT_CODE=$?
          xcodebuild -showBuildSettings -scheme "$SCHEME" > xcodebuild.log 2>&1 || true
          exit ${EXIT_CODE:-0}

      - name: Create IPA manually (no exportArchive)
        working-directory: Jarvis
        env:
          ARCHIVE_PATH: ${{ github.workspace }}/Jarvis/build/Jarvis.xcarchive
          EXPORT_DIR: ${{ github.workspace }}/Jarvis/build/export
        run: |
          set -o pipefail
          mkdir -p "$EXPORT_DIR/Payload"
          # Copy .app from archive into Payload
          cp -R "$ARCHIVE_PATH/Products/Applications/"*.app "$EXPORT_DIR/Payload/"
          # Clean extended attributes
          xattr -rc "$EXPORT_DIR/Payload"
          # Zip Payload into IPA
          cd "$EXPORT_DIR"
          /usr/bin/zip -qry "Jarvis-unsigned.ipa" Payload
          echo "IPA created at: $EXPORT_DIR/Jarvis-unsigned.ipa"
          ls -la "$EXPORT_DIR"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: Jarvis/build/export/Jarvis-unsigned.ipa
          if-no-files-found: error

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            Jarvis/xcodebuild.log
