# .github/workflows/build-ipa.yml
# Full workflow that:
# 1) Installs XcodeGen
# 2) Generates Jarvis/Jarvis.xcodeproj from Jarvis/project.yml
# 3) Archives the app unsigned
# 4) Packages an unsigned IPA suitable for AltStore

name: Generate Project and Build IPA

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Show layout (debug)
        run: |
          pwd
          ls -la
          echo "--- Jarvis ---"
          ls -la Jarvis || true

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project (spec is Jarvis/project.yml)
        working-directory: Jarvis
        run: xcodegen generate

      - name: Verify project created
        run: |
          ls -la Jarvis
          test -d Jarvis/Jarvis.xcodeproj || (echo "Missing Jarvis/Jarvis.xcodeproj" && exit 1)

      - name: List schemes
        run: xcodebuild -list -project Jarvis/Jarvis.xcodeproj

      - name: Archive (Release, unsigned)
        env:
          ARCHIVE_PATH: ${{ github.workspace }}/build/Jarvis.xcarchive
        run: |
          set -o pipefail
          xcodebuild clean archive \
            -project Jarvis/Jarvis.xcodeproj \
            -scheme Jarvis \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
            IPHONEOS_DEPLOYMENT_TARGET=17.0 \
            ENABLE_BITCODE=NO
          xcodebuild -showBuildSettings -project Jarvis/Jarvis.xcodeproj -scheme Jarvis > xcodebuild.log 2>&1 || true

      - name: Inspect archive contents
        run: |
          find build/Jarvis.xcarchive -maxdepth 3 -print || true

      - name: Create IPA manually (no exportArchive)
        env:
          ARCHIVE_PATH: ${{ github.workspace }}/build/Jarvis.xcarchive
          EXPORT_DIR:   ${{ github.workspace }}/build/export
        run: |
          set -o pipefail
          APP_DIR="$ARCHIVE_PATH/Products/Applications"
          echo "Searching for .app under: $APP_DIR"
          APP_PATH="$(find "$APP_DIR" -maxdepth 1 -name "*.app" -print -quit)"
          if [ -z "$APP_PATH" ]; then
            echo "No .app found. Ensure the scheme builds an iOS App and archive succeeded."
            exit 1
          fi
          echo "Found app: $APP_PATH"
          mkdir -p "$EXPORT_DIR/Payload"
          cp -R "$APP_PATH" "$EXPORT_DIR/Payload/"
          xattr -rc "$EXPORT_DIR/Payload"
          (cd "$EXPORT_DIR" && /usr/bin/zip -qry "Jarvis-unsigned.ipa" Payload)
          ls -la "$EXPORT_DIR"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/export/Jarvis-unsigned.ipa
          if-no-files-found: error

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: xcodebuild.log
