# .github/workflows/build-ipa.yml
# CI pipeline that:
# - Checks out repo with submodules (mlcllm at external/mlcllm)
# - Installs toolchains (CMake, Rust, XcodeGen)
# - Configures & builds mlcllm iOS device static libs with CMake
#   using a compatibility override: -DCMAKE_POLICY_VERSION_MINIMUM=3.5
#   (source = external/mlcllm, build/install prefix = external/mlcllm/ios/build)
# - Stages libs (and optional bundle) into Jarvis/dist/*
# - Generates the Xcode project from Jarvis/project.yml
# - Builds, archives unsigned, and produces an unsigned IPA

name: Generate Project and Build IPA

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Debug layout
        shell: bash
        run: |
          echo "== Repo root ==" && pwd
          ls -la
          echo "== Jarvis dir ==" && ls -la Jarvis || true
          echo "== Submodule dir ==" && ls -la external || true
          ls -la external/mlcllm || true
          echo "== Key files =="
          test -f Jarvis/project.yml && echo "Jarvis/project.yml: OK" || echo "Jarvis/project.yml: MISSING"
          test -f Jarvis/Package.swift && echo "Jarvis/Package.swift: OK" || echo "Jarvis/Package.swift: MISSING"
          test -f Jarvis/Sources/AppModule/App/Info.plist && echo "Info.plist: OK" || echo "Info.plist: MISSING"
          test -f external/mlcllm/CMakeLists.txt && echo "mlcllm CMakeLists.txt: OK" || echo "mlcllm CMakeLists.txt: MISSING"

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install build tools (CMake, Rust, XcodeGen)
        shell: bash
        run: |
          set -euxo pipefail
          brew install cmake xcodegen rustup-init || true
          if ! command -v rustup >/dev/null 2>&1; then
            rustup-init -y
          fi
          # Expose cargo to subsequent steps (must be KEY=VALUE lines)
          echo "CARGO_HOME=$HOME/.cargo" >> "$GITHUB_ENV"
          echo "PATH=$HOME/.cargo/bin:$PATH" >> "$GITHUB_ENV"
          cmake --version
          xcodegen --version
          rustc --version || true
          rustup --version || true

      - name: Configure and build mlcllm (iOS arm64, device) with CMake policy override
        shell: bash
        run: |
          set -euxo pipefail
          SRC="$GITHUB_WORKSPACE/external/mlcllm"                 # contains CMakeLists.txt
          BUILD="$GITHUB_WORKSPACE/external/mlcllm/ios/build"     # libs will be installed under ios/build
          mkdir -p "$BUILD"
          # Add Rust target for iOS device (as prepare_libs.sh would)
          rustup target add aarch64-apple-ios || true
          # Configure (include compatibility override for old nested CMake projects)
          cmake -S "$SRC" -B "$BUILD" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_SYSTEM_VERSION=14.0 \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 \
            -DCMAKE_BUILD_WITH_INSTALL_NAME_DIR=ON \
            -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON \
            -DCMAKE_INSTALL_PREFIX="$BUILD" \
            -DCMAKE_CXX_FLAGS="-O3" \
            -DMLC_LLM_INSTALL_STATIC_LIB=ON \
            -DUSE_METAL=ON \
            -DTVM_FFI_USE_LIBBACKTRACE=OFF \
            -DTVM_FFI_BACKTRACE_ON_SEGFAULT=OFF \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          # Build & install static libs
          cmake --build "$BUILD" --config release --target mlc_llm_static -j
          cmake --build "$BUILD" --target install --config release -j
          echo "== Built static libs =="
          find "$BUILD" -maxdepth 3 -type f -name "*.a" -print || true

      - name: Stage mlcllm libs and optional bundle into Jarvis/dist
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p Jarvis/dist/lib Jarvis/dist/bundle
          # Copy installed static libs from the submodule build
          if [ -d external/mlcllm/ios/build/lib ]; then
            cp -R external/mlcllm/ios/build/lib/*.a Jarvis/dist/lib/ || true
          fi
          # Optionally copy runtime bundle assets if present in your submodule
          if [ -d external/mlcllm/ios/prebuilt/bundle ]; then
            cp -R external/mlcllm/ios/prebuilt/bundle/* Jarvis/dist/bundle/ || true
          fi
          if [ -d external/mlcllm/ios/MLCGen/output/bundle ]; then
            cp -R external/mlcllm/ios/MLCGen/output/bundle/* Jarvis/dist/bundle/ || true
          fi
          echo "== Dist lib =="
          ls -la Jarvis/dist/lib || true
          echo "== Dist bundle =="
          ls -la Jarvis/dist/bundle || true
          echo "== Architectures of libs =="
          shopt -s nullglob
          for f in Jarvis/dist/lib/*.a; do
            file "$f" || true
            lipo -info "$f" || true
          done

      - name: Clean any stale project
        shell: bash
        run: rm -rf Jarvis/Jarvis.xcodeproj

      - name: Generate Xcode project (run inside Jarvis/)
        working-directory: Jarvis
        shell: bash
        run: xcodegen generate

      - name: Verify project and artifacts
        shell: bash
        run: |
          set -euxo pipefail
          test -d Jarvis/Jarvis.xcodeproj || (echo "Missing Jarvis/Jarvis.xcodeproj" && exit 1)
          test -f Jarvis/Package.swift || (echo "Missing Jarvis/Package.swift" && exit 1)
          test -f Jarvis/Sources/AppModule/App/Info.plist || (echo "Missing Info.plist" && exit 1)
          ls -la Jarvis/dist/lib || true
          ls -la Jarvis/dist/bundle || true

      - name: List schemes
        shell: bash
        run: xcodebuild -list -project Jarvis/Jarvis.xcodeproj

      - name: Build (optional fast fail)
        shell: bash
        run: |
          set -o pipefail
          xcodebuild clean build \
            -project Jarvis/Jarvis.xcodeproj \
            -scheme Jarvis \
            -configuration Release \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
            IPHONEOS_DEPLOYMENT_TARGET=17.0

      - name: Archive (Release, unsigned)
        env:
          ARCHIVE_PATH: ${{ github.workspace }}/build/Jarvis.xcarchive
        shell: bash
        run: |
          set -o pipefail
          xcodebuild clean archive \
            -project Jarvis/Jarvis.xcodeproj \
            -scheme Jarvis \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
            IPHONEOS_DEPLOYMENT_TARGET=17.0 \
            ENABLE_BITCODE=NO
          xcodebuild -showBuildSettings -project Jarvis/Jarvis.xcodeproj -scheme Jarvis > xcodebuild.log 2>&1 || true

      - name: Inspect archive contents
        shell: bash
        run: |
          find build/Jarvis.xcarchive -maxdepth 3 -print || true

      - name: Create IPA manually (no exportArchive)
        env:
          ARCHIVE_PATH: ${{ github.workspace }}/build/Jarvis.xcarchive
          EXPORT_DIR:   ${{ github.workspace }}/build/export
        shell: bash
        run: |
          set -o pipefail
          APP_DIR="$ARCHIVE_PATH/Products/Applications"
          APP_PATH="$(find "$APP_DIR" -maxdepth 1 -name "*.app" -print -quit)"
          if [ -z "$APP_PATH" ]; then
            echo "No .app found. Ensure the scheme builds an iOS App and archive succeeded."
            exit 1
          fi
          mkdir -p "$EXPORT_DIR/Payload"
          cp -R "$APP_PATH" "$EXPORT_DIR/Payload/"
          xattr -rc "$EXPORT_DIR/Payload"
          (cd "$EXPORT_DIR" && /usr/bin/zip -qry "Jarvis-unsigned.ipa" Payload)
          ls -la "$EXPORT_DIR"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/export/Jarvis-unsigned.ipa
          if-no-files-found: error

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: xcodebuild.log
