# This workflow will build and test a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Set up Swift 5.9
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'

      - name: Verify Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version

      - name: Cache Swift packages
        uses: actions/cache@v3
        with:
          path: |
            Jarvis/.build
            Jarvis/Packages
          key: ${{ runner.os }}-swift-${{ hashFiles('Jarvis/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-

      - name: Build the package
        working-directory: Jarvis
        run: |
          swift package clean
          swift build -v

      - name: Run tests
        working-directory: Jarvis
        run: swift test -v
