name: Swift

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Set up Swift 6
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Verify submodule exists
        run: |
          ls -la Jarvis/ThirdParty/
          ls -la Jarvis/ThirdParty/mlc-llm/ios/ || echo "MLCSwift folder not found"

      - name: Build the package
        working-directory: Jarvis
        run: |
          swift package clean
          swift build -v
