# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "Develop" ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2' # or any 16.x version available on macos-latest

      - name: Set up Swift 5.9
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'

      - name: Verify Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version

      - name: Generate Xcode project
        run: swift package generate-xcodeproj

      - name: Build with Xcode
        run: |
          xcodebuild clean build \
          -project Jarvis.xcodeproj \
          -scheme Jarvis \
          -destination "generic/platform=iOS" \
          IPHONEOS_DEPLOYMENT_TARGET=18.0 \
          CODE_SIGN_STYLE=Automatic \
          -allowProvisioningUpdates
